name: 'Valley Entrepreneur '
favicon: null
layout_spectrum: 0.49639
typography_spectrum: 0.37814
title: The Path to Entrepreneurship
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.375
  lightness: 0.5625
  saturation: 0.2545503620058298
  rhythmicContrast: 0.5
purpose: []
